Move functions in locallib.php to a class object groups
accredible/moodle-mod_accredible pull request #36
Opened 2021-09-24 14:04 UTC by kei178

WIP

2021-09-28 14:10 UTC, naveenbalachandar requested changes
<img width="827" alt="Screenshot 2021-09-28 at 7 31 18 PM" src="https://user-images.githubusercontent.com/77011560/135102229-8081c6e9-7710-4df1-9879-8d15b2dd0803.png">
@kei178 The code-checker gives out some errors for groups_test.php
Could you please take a look at this as well.

2021-09-29 06:59 UTC, kei178 commented on classes/local/groups.php
> +        $response = $this->apiRest->search_groups(10000, 1);
'search_groups' has already been covered by existing unit tests.

2021-09-29 08:09 UTC, kei178 commented
@naveenbalachandar - I added unit tests for the group-related functions in apiRest.php. I also updated the coding style in groups_test.php.

<img width="719" alt="Screen Shot 2021-09-29 at 10 08 44" src="https://user-images.githubusercontent.com/20009662/135228855-9d871eb3-4820-40d8-9a6f-c2f7d83c247c.png">

2021-09-29 12:52 UTC, kei178 commented
@naveenbalachandar - Fixed the coding style error in apiRest_test.php.

2021-09-30 11:02 UTC, naveenbalachandar approved these changes
LGTM!

2021-09-30 11:35 UTC, merged