Feature/ntgr 48/move locallib functions to class directory
accredible/moodle-mod_accredible pull request #37
Opened 2021-09-28 08:52 UTC by naveenbalachandar

## Description of the change

Moved the following functions in locallib.php to a new classes/local/credentials.php

- `accredible_get_credentials` -> `credentials->get_credentials`
- `create_credential` -> `credentials->create_credential`
- `create_credential_legacy` -> `credentials->create_credential_legacy`
- `accredible_check_for_existing_credential` -> `credentials->check_for_existing_credential`
- `accredible_check_for_existing_certificate` -> `credentials->check_for_existing_certificate`

All coding style standards from the code-checker plugin has been followed for the new additions.

## Testing
- Added unit tests for all the above functions in tests/classes/local/credentials_test.php
- Added unit tests for get_credentials, create_credentials api calls in tests/classes/apiRest/apiRest_test.php

## Manual testing

**credentials->get_credentials**
- Click on any accredible activity with existing credential
- The view page will call this function to fetch all credentials of the group

**credentials->create_credential**
- Add an accredible activity and manually trigger a certificate issue.
- This function will be called to create a new credential using the public accredible API

**credentials->create_credential_legacy** (legacy)
- change the if statement in lib.php#128 to always fail and update the database table -> mdl_accredible to have a achievement_id (group_name)
- Edit an existing accredible activity and add a new user under the "Manually issue certificates/badges" and save

**credentials->check_for_existing_credential**
- Add a final quiz to the course and trigger it for course completion.
- Login as a student and attempt the quiz and submit
- The accredible_quiz_submission_handler will call this function to check if a credential exists for a user

**credentials->check_for_existing_certificate** (legacy)
- Edit line 357 in locallib.php and trigger the else statement
- repeat the steps for credentials->check_for_existing_credential

2021-09-28 19:15 UTC, kei178 requested changes
I haven't done manual testing yet. I left three comments. Aside from that it all looks good.

2021-09-29 06:35 UTC, kei178 commented on tests/classes/local/credentials_test.php
> +    }
The following example would be more suitable than `willReturnOnConsecutiveCalls` for the pagination test case.

```php
$mock->expects($this->at(0))
    ->method('foo')
    ->with(...)
    ->will($this->returnValue(...));

$mock->expects($this->at(1))
    ->method('foo')
    ->with(...)
    ->will($this->returnValue(...));
```

2021-09-29 10:46 UTC, naveenbalachandar commented on classes/local/credentials.php
> +            }
Makes sense. I have removed this logic as it is not being used and removed the argument.

2021-09-29 10:49 UTC, naveenbalachandar commented on tests/classes/local/credentials_test.php
> +    }
`$this->at()` is deprecated and will be removed from PHPUnit 10.
So I have used withConsecutive and onConsecutiveCalls for this.

2021-09-29 11:52 UTC, kei178 approved these changes
LGTM.

2021-10-01 06:41 UTC, kei178 commented
This branch will be merged into `develop` after the current QA process is completed.

2021-10-11 11:31 UTC, merged