fix all code-checker error and warnings in Html2Text.php
accredible/moodle-mod_accredible pull request #46
Opened 2021-10-04 09:00 UTC by naveenbalachandar

Fixed the errors and warnings from code-checker in Html2Text.php.
With this PR all errors and warnings from code-checker have been fixed.
The accredible module plugin now follows the moodle coding style.

<img width="712" alt="Screenshot 2021-10-04 at 2 27 09 PM" src="https://user-images.githubusercontent.com/77011560/135822692-92cc7716-5fea-48cb-a53a-4292783ce9c8.png">

<img width="1012" alt="Screenshot 2021-10-04 at 2 26 00 PM" src="https://user-images.githubusercontent.com/77011560/135822581-1e966a1e-b3dd-478d-b4f6-5ed950908721.png">

2021-10-04 09:01 UTC, naveenbalachandar commented on classes/Html2Text/Html2Text.php
> +                    && !($n instanceof \DOMText && static::is_whitespace($text))) {
Removed else from here as moodle coding style doesn't allow empty if block.

2021-10-04 12:34 UTC, kei178 requested changes
@naveenbalachandar - The current changes look good to me. I'd like to request additional two changes as follows:
 
1. Please add `defined('MOODLE_INTERNAL') || die();` at line#18 right after the `namespace` because it causes a warning below.

<img width="743" alt="Screen Shot 2021-10-04 at 14 31 08" src="https://user-images.githubusercontent.com/20009662/135851699-5a7c9972-8e06-4502-9fc9-da79b4fdc64e.png">

2. It does not raise any coding style errors or warnings, but it would be more appropriate to rename the directory and the class `Html2Text` to `html2text` to meet the requirement [here](https://docs.moodle.org/dev/Coding_style#Classes):

> Class names should always be lower-case English words, separated by underscores:

2021-10-05 12:17 UTC, kei178 commented
> 2. It does not raise any coding style errors or warnings, but it would be more appropriate to rename the directory and the class Html2Text to html2text to meet the requirement here:

@naveenbalachandar - Let’s leave it for now in case we want to override the Moodle core class `Html2Text` in the future.

2021-10-05 12:18 UTC, kei178 approved these changes
LGTM

2021-10-05 12:18 UTC, merged